### ISSUE TITLE
No detection results on api.credo.science for the user: Peter

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#45]
I received a message from the user:

Hi - I've been running the CREDO app overnight for a couple of weeks and don't see any of my detections on the website.
I tried https://api.credo.science/web/user/Peter/ but it shows 'Number of detections: 0 (no place)'
Can you help?
Thanks,

additional information
Do you have wifi enabled while the application is running?
Yes

How long do you work on the application
2 weeks (approx)

- How many detections do you have in the application?
78 since 2018-12-02

- How much time has passed since the detection of the last detection?
Last detection: 2018-12-10 07:21:22:661

- Your username ("Login") and visible name.  
peterj.briggs@gmail.com      Peter

Can you check why there are no results for this user at api.credo.science?

**Comment by koziomek** [comment]
Because the provided link leads to another user's profile. (login: 'Peter', display name: 'Peter')

The user sending the email has login 'peterb' and display name 'Peter'.
That means that the valid link to their profile is:
https://api.credo.science/web/user/peterb/

Not visible detections for this user were classified as hot-pixels.

**Comment by slawekstu** [comment]
Thank you for your response
